spring:
  application:
    name: microservice2
  datasource:
    url: jdbc:postgresql://localhost:5432/Banco
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true