version: "3.8"
services:
  frontend:
    container_name: FrontContainer
    build:
      context: ./vite-project  
      dockerfile: Dockerfile
    image: shezy1/frontimage:latest 
    ports:
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    container_name: BackContainer
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    image: shezy1/backimage:latest 
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=Prestabanco
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
  jenkins:
    container_name: JenkinsContainer
    image: shezy1/jenkinsimage:latest
    ports:
      - "8080:8080"  
      - "50000:50000"  
    volumes:
      - jenkins_home:/var/jenkins_home  
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    container_name: DBContainer
    image: postgres:latest 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Prestabanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  jenkins_home:
