server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: microservice1
          uri: http://ms1-service:8081 # Cambia "lb://microservice1" por el nombre del servicio Kubernetes
          predicates:
            - Path=/api/creditsimulation/**
        - id: microservice2
          uri: http://ms2-service:8082 # Cambia "lb://microservice2" por el nombre del servicio Kubernetes
          predicates:
            - Path=/api/register/**
        - id: microservice3
          uri: http://ms3-service:8083 # Cambia "lb://microservice3" por el nombre del servicio Kubernetes
          predicates:
            - Path=/api/credit-request/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka # Cambia "localhost" por el nombre del servicio Kubernetes de Eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
