server:
  port: 8080  # Cambié el puerto del API Gateway a 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: credit-simulation-service
          uri: lb://credit-simulation-service
          predicates:
            - Path=/api/creditsimulation/**
        - id: user-registration-service
          uri: lb://user-registration-service
          predicates:
            - Path=/api/register/**
        - id: new-service
          uri: lb://new-service
          predicates:
            - Path=/api/newservice/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Cambié la URL de Eureka a un servidor local
