spring:
  application:
    name: microservice2  # Nombre del microservicio

  datasource:
    url: jdbc:postgresql://localhost:5432/Banco  # URL de la base de datos
    username: postgres  # Usuario para la base de datos
    password: 123456  # Contraseña para la base de datos
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Tamaño máximo del pool de conexiones
      connection-timeout: 30000  # Timeout para la conexión

  jpa:
    hibernate:
      ddl-auto: update  # Establece el comportamiento de actualización de la base de datos
    show-sql: true  # Muestra las consultas SQL en los logs
    properties:
      hibernate.format_sql: true  # Formatea las consultas SQL para que sean legibles

  cloud:
    config:
      uri: http://localhost:8888  # URI del servidor de Config
      name: microservice2  # Nombre del microservicio que se registrará en el servidor Config
      profile: default  # El perfil predeterminado para la configuración
