server:
  port: 8081

spring:
  application:
    name: credit-simulation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_simulation_db
    username: credit_user
    password: credit_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
