server:
  port: ${PORT:8081} # El puerto se configura con una variable de entorno, 8081 es el valor por defecto

spring:
  application:
    name: microservice1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/ # Cambiado a "eureka-service" para Kubernetes
  instance:
    prefer-ip-address: true
