spring:
  application:
    name: microservice3 # Nombre del microservicio, usado para identificar su configuración
    cloud:
      config:
        uri: http://localhost:8888  # URI del servidor de Config
        profile: default  # El perfil predeterminado para la configuración

  datasource:
    url: jdbc:postgresql://localhost:5432/Banco3 # Base de datos para microservicio 3
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Define si se deben crear/modificar tablas automáticamente
    show-sql: true # Muestra las consultas SQL en los logs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL del servidor Eureka

# Si necesitas otras configuraciones, puedes agregarlas aquí
logging:
  level:
    org.springframework: DEBUG # Nivel de logging, útil para depuración en desarrollo

