apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2-deployment
  labels:
    app: ms2-deployment
spec:
  selector:
    matchLabels:
      app: ms2-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms2-deployment
    spec:
      containers:
        - name: ms2
          image: shezy1/microservice2:latest  # Reemplaza con la imagen de microservicio 2
          ports:
            - containerPort: 8082  # Puerto donde escucha el microservicio
          env:
            - name: SERVER_PORT
              value: "8082"  # El puerto que escucha en el contenedor
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map  # ConfigMap que contiene DB_HOST
                  key: DB_HOST_MS2  # Clave dentro del ConfigMap
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_MS2  # Clave dentro del ConfigMap
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_MS2  # Clave dentro del ConfigMap
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map  # Usamos el ConfigMap para las credenciales
                  key: DB_USER_MS2  # Clave dentro del ConfigMap
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map  # Usamos el ConfigMap para las credenciales
                  key: DB_PASSWORD_MS2  # Clave dentro del ConfigMap
---
apiVersion: v1
kind: Service
metadata:
  name: ms2-service
  labels:
    app: ms2
spec:
  selector:
    app: ms2-deployment  # Selector que debe coincidir con el Deployment
  ports:
    - protocol: TCP
      port: 8082  # Puerto del servicio
      targetPort: 8082  # Puerto dentro del contenedor
  type: ClusterIP  # Tipo de servicio, se puede cambiar a NodePort si es necesario
