server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DieguinFC/TingesoProyecto2
          default-label: main
          search-paths: "config-data"
