server:
  port: 8761 # Puerto donde estará disponible Eureka

spring:
  application:
    name: eureka-server
  cloud:
    config:
      import: configserver:http://localhost:8888 # Asegúrate de que esta URL sea la correcta

eureka:
  client:
    register-with-eureka: false # El servidor no se registra a sí mismo
    fetch-registry: false       # No obtiene registros de otros servidores
  instance:
    hostname: localhost
