server:
  port: 8080  # Puerto donde estará disponible el API Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: lb://microservice1
          predicates:
            - Path=/api/creditsimulation/**
        - id: microservice2
          uri: lb://microservice2
          predicates:
            - Path=/api/register/**
    discovery:
      locator:
        enabled: true
    config:
      enabled: false  # Desactiva la búsqueda de Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
